# -*- coding:utf-8 -*-

# Given two strings s and t which consist of only lowercase letters.
#
# String t is generated by random shuffling string s and then add one more letter at a random position.
#
# Find the letter that was added in t.
#
# Example:
#
# Input:
# s = "abcd"
# t = "abcde"
#
# Output:
# e
#
# Explanation:
# 'e' is the letter that was added.


class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        t_l = [0] * 26
        for c in t:
            t_l[ord(c) - ord('a')] += 1

        for c in s:
            t_l[ord(c) - ord('a')] -= 1

        return ''.join([v * chr(i + ord('a')) for i, v in enumerate(t_l) if v != 0])


if __name__ == '__main__':
    s = "abcd"
    t = "abcde"
    solution = Solution()
    r = solution.findTheDifference(s, t)

    print r